### ISSUE TITLE
Crashing while loading data using API

### ISSUE THREAD

**Issue by KiranYechuri** [HocTran/WatchLayout#3]
I am using watch layout for collection view .while assigning data from api app is crashing in watchLayout.swift . 
<img width="1147" alt="Screenshot 2021-08-16 at 4 32 13 PM" src="https://user-images.githubusercontent.com/44187154/129554298-0b7147a1-ed1a-423d-b628-ba1caac45f5a.png">

**Comment by HocTran** [comment]
It's likely the wrong index passed into the function @KiranYechuri .

The `centeredOffsetForItem()` is a public function, then the host datasource should be responsible for the index.
Did you `reloadData` and then make sure the `indexPath` is in the item range? (basically the attributes count is equal to  the datasource items count)

Otherwise, can you please provide the stack trace?
